packaging_format = 2

id = "qbittorrent"
name = "qBittorrent"
description.en = "A bittorrent client that aims to be a good alternative to all other bittorrent clients."
description.fr = ""

version = "4.2.5~ynh.1"

maintainers = ["kay0u"]

[upstream]
license = "GPL-3.0-or-later"
website = "hhttps://www.qbittorrent.org"
admindoc = "https://github.com/qbittorrent/qBittorrent/wiki"
code = "https://github.com/qbittorrent/qBittorrent"
cpe = "cpe:2.3:a:qbittorrent:qbittorrent"

[integration]
yunohost = ">= 11.1.10"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/qbittorrent"

    [install.admin]
    type = "user"

    #[install.init_main_permission]
    ## this is a generic question - ask strings are automatically handled by YunoHost's core
    ## This won't be saved as setting and will instead be used to initialize the SSOwat permission
    #type = "group"
    #default = "visitors"

    #[install.password]
    ## this is a generic question - ask strings are automatically handled by YunoHost's core
    ## Note that user-provided passwords questions are not automatically saved as setting
    #help.en = "Use the help field to add an information for the admin about this question."
    #help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    #type = "password"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 30000

    [resources.apt]
    packages = "qbittorrent-nox"
