#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="qBittorrent-nox service" --log="$install_dir/.local/share/data/qBittorrent/logs/qbittorrent.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

mkdir -p "$install_dir/.config/qBittorrent/"

ynh_config_add --template="qBittorrent.conf" --destination="$install_dir/.config/qBittorrent/qBittorrent.conf"

chown -R $app: "$install_dir"

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir

ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="share/Torrents"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action=start --wait_until="Web UI: Now listening on IP: \*, port: $port" --log_path="$install_dir/.local/share/data/qBittorrent/logs/qbittorrent.log" --timeout=60

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
