#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIR
#=================================================

ynh_restore "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

log_dir="$data_dir/.local/share/data/qBittorrent/logs"
mkdir -p "$log_dir"
touch "$log_dir/qbittorrent.log"

yunohost service add $app --description="qBittorrent-nox service" --log="$log_dir/qbittorrent.log"

chown -R $app: "$data_dir"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

# Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemctl --service=$app --action=start --wait_until="To control qBittorrent" --log_path="systemd" --timeout=180

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
